plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.myapp'
    compileSdk 37

    defaultConfig {
        minSdk 26
        targetSdk 37
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    kotlin {
        jvmToolchain(17)
    }
}

// This block explicitly forces the compiler to ignore the version mismatch
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions.freeCompilerArgs.add("-Xskip-metadata-version-check")
}

dependencies {
    implementation 'org.mozilla.geckoview:geckoview:156.0.20260921121718'
}
